### ISSUE TITLE
Improve user contact interaction

### ISSUE THREAD

**Issue by Createdd** [DevelopersRising/DevelopersRising.github.io#14]
@dhelic98 Regarding you comment on #5: 

Feel free to act on it. I would recommend using a modal, but it's up to you ;) 
How do you make the form working in practice? Since a working form needs to be tied to a server somewhere and this page is currently hosted on Github Pages. 
Happy for your ideas!

**Comment by dhelic98** [comment]
@DDCreationStudios Hello, I know that therefore I would suggest using formspree service which I have used before, but it is only free for 1000 submissions per month per e-mail, so I believe that would be enough to get the page started.

**Comment by Createdd** [comment]
@dhelic98  cool idea! I have never heard of it! From my side you can do it that way :) 

What are your thoughts @robeerob ?

**Comment by robaxelsen** [comment]
@DDCreationStudios Haven't used formspree myself. But maybe we should consider simply using Google Forms? Easy to set up, and we already have a gmail account for the organization.

@dhelic98 any thoughts on formspree vs google forms?

**Comment by MadhavBahl** [comment]
@DDCreationStudios  i have an idea for contact interaction, lets add a contact us form and a sort of feedback form, which on submissiono, sends the feedback/message to the official email id of developers rising and also sends a thank you message to the client. We can do this easily usinng nodemailer.

for example, 
![image](https://user-images.githubusercontent.com/26179770/31885692-06ad323c-b80f-11e7-93ef-2ed69b2a774d.png)

**Comment by robaxelsen** [comment]
@MadhavBahlMD Sounds good to me! I would welcome a PR for this.

@DDCreationStudios what do you think?

**Comment by MadhavBahl** [comment]
Ok i will do it, 
send me the credentials of gmail id which you want to use for contact purpose and sending thankyou message.
mail me that on madhavbahl10@gmail.com

**Comment by MadhavBahl** [comment]
And one more thing, we will have to use another hosting service like heroku  (i will add the steps for deployment in README ) because, github hosting only supports static pages, it wont support node.js and nodemailer.
Heroku is awesome and easy, i will add complete proceedure of deployment.
I will wait for a confirmation before starting my work.

**Comment by robaxelsen** [comment]
@MadhavBahlMD That complicates it a little bit for us. Would you be able to do this using a free service that does not require hosting, or use something simple like Google Forms/Formspree/etc?

Our gmail address is devsrising@gmail.com.

**Comment by MadhavBahl** [comment]
I would suggest abdding backend part to make the website more dynamic and sustainable for future development ideas. Because if developers rising community grows, then at some point of time, we will have to include backend for things like managing resources and making databases.
It is not complicated and it will be great, and i will add complete documentation in the README.
The final decision is yours. I would be glad to help 😃

**Comment by robaxelsen** [comment]
@DDCreationStudios any thoughts?

**Comment by Createdd** [comment]
@MadhavBahlMD yeah good point! Feel free to do it :) And thanks a lot :)

**Comment by MadhavBahl** [comment]
I am on it. 👍 💯

**Comment by MadhavBahl** [comment]
@robeerob @DDCreationStudios  i will create another repo for development and testing purposes, and commit the changes to that, then we can have this static website live even if we are developing the dynamic one

**Comment by MadhavBahl** [comment]
I just realized, there is no need for a separate repository.
@robeerob you can delete this https://github.com/DevelopersRising/Developers-Rising-Website . Sorry for the confusion :(

**Comment by robaxelsen** [comment]
@MadhavBahlMD done!

**Comment by MadhavBahl** [comment]
Contact us form is added in index.html and nodeJS server is created.
PROCEEDURE.md --> 

NOTE** Replace "YOUR_PASSWORD_HERE" in /serverFiles/mailer.js to your real password, only then it will work.

1. install NodeJS
2. Open your local repository directory in command prompt

![image](https://user-images.githubusercontent.com/26179770/31987997-360570da-b98b-11e7-8b47-bb762d6f4072.png)

3. run   **npm install**
4. run **node server.js**

![image](https://user-images.githubusercontent.com/26179770/31988043-61650ede-b98b-11e7-9725-782260681762.png)

5. Open browser and type localhost:8080 and press enter
![image](https://user-images.githubusercontent.com/26179770/31988083-855171d4-b98b-11e7-8b82-f29d51833f5e.png)

6. Create an account on heroku and follow heroku nodeJS deploy proceedure from any youtube video

NOTE** if you just want the static website, then just keep the public directory. :)

**Comment by Createdd** [comment]
improved with #26 . ready for close
