### ISSUE TITLE
Extend the about section with

### ISSUE THREAD

**Issue by Createdd** [DevelopersRising/DevelopersRising.github.io#18]
the following:
___

Our goal is to help, connect and inspire. Here are some of the things we've accomplished:

1000+ Meetup Members
20+ Successful Free Meetups
20+ Awesome Speakers
5+ Sponsors And Partners Involved
4+ Active Open Source Repos
Founded 3 Meetup Groups
___

See on https://github.com/DevelopersRising/DevelopersRising/issues/38 for more

**Comment by Ashwin-Kapes** [comment]
I would like to try this.

**Comment by Createdd** [comment]
@Ashwin-Kapes  Go for it ;)
