### ISSUE TITLE
Add margin-top in "Contact Us" section

### ISSUE THREAD

**Issue by robaxelsen** [DevelopersRising/DevelopersRising.github.io#33]
Just noticed that we could need some extra margin at the top of the "Contact Us" section.

![screenshot from 2017-11-04 08-50-22](https://user-images.githubusercontent.com/13132899/32403567-a2e47354-c13d-11e7-8fac-55531e6e1844.png)

**Comment by Createdd** [comment]
Yep, I want to change some things anyways. Will add you for review when everything is finished :)
