### ISSUE TITLE
feedback for sending messages is not working

### ISSUE THREAD

**Issue by Createdd** [DevelopersRising/DevelopersRising.github.io#43]

**Comment by Createdd** [comment]
change of passwort in env needed; working on it

**Comment by Createdd** [comment]
![image](https://user-images.githubusercontent.com/22077628/36268091-eb11992a-1275-11e8-9f85-3d2cc35be607.png)
google blocked it @robaxelsen  this is the user from dublin hahahahaha

**Comment by Createdd** [comment]
fixed now

**Comment by robaxelsen** [comment]
Ah, haha. Well done @DDCreationStudios!
