### ISSUE TITLE
Contact form not working

### ISSUE THREAD

**Issue by robaxelsen** [DevelopersRising/DevelopersRising.github.io#44]
Contact form is not working. Timeouts and gives heroku error:

![Screenshot at 2019-04-11 17-12-12](https://user-images.githubusercontent.com/13132899/55968895-2f8dcb80-5c7d-11e9-8e79-71987c8516db.png)

**Comment by robaxelsen** [comment]
I will investigate.

**Comment by Createdd** [comment]
thanks! I always receive this google security warnings. i am really annoyed by it. let me know if you can fix otherwise we can also deactivate it :)

**Comment by robaxelsen** [comment]
The issue is caused by using outdated (legacy) OAuth authentication, which is not supported anymore: https://github.com/nodemailer/nodemailer/issues/847

Instead of updating the code to use OAuth with Nodemailer v4+, I suggest we simply replace the form with a sign up form for our newsletter. What do you think, @Createdd?

**Comment by Createdd** [comment]
Hi @robaxelsen ,
thanks for having a look at it! :) Sure thats an option. But should we even remove it? As we aren't 100% sure if we should keep the Verein, it would be even better to remove it completely. 
What do you think? Shall I do it?

**Comment by robaxelsen** [comment]
Good idea. Yes, your offer is accepted with thanks! 🎉🤟

**Comment by Createdd** [comment]
alright! :) 
will do it either tomorrow or the next days :)

**Comment by Createdd** [comment]
put it directly on the master branch for simplicity: https://github.com/DevelopersRising/DevelopersRising.github.io/commit/28fbfd7718f57e2fa4b94975f2fd21c1ca271ffd

**Comment by robaxelsen** [comment]
@Createdd Awesome, thanks!
