### ISSUE TITLE
Add an about site

### ISSUE THREAD

**Issue by Createdd** [DevelopersRising/DevelopersRising.github.io#5]
- create an own about.html
  - and add different sections explaining what we as a verein want to do
  - see the [FCCVienna](https://github.com/FCCVienna/FCCVienna) repo for more information 
- add a link in the navebar
- feel free to add your thoughts and ideas that might fit into the about page (also design)
- to get a feeling of some principles we also share, see [Y Combinator's Founding Principles](http://www.ycombinator.com/principles/)

**Comment by PallaviDas07** [comment]
I am interested. I will be glad to work on it. Can you give me the details of what needs to be added in about.html ? Can you please elaborate the first proposal point again?

**Comment by Createdd** [comment]
@PallaviDas07 HI! Thanks for reaching out! I have updated the issue. Can you now work with that? Feel free to add some things and open a pull request. We will add reviews and change requests to get a more iterative workflow going. We are open for suggestions :) 

Also note, that we as organizers are currently in the stage of working on some text for the about page, so we likely will add and change paragraphs anyways. 

I will also create other issues, if you want to work on something else :)

**Comment by PallaviDas07** [comment]
@DDCreationStudios Thank you!  I will be glad to contribute. Will I create and add a link to the about page then for the time being?

**Comment by dhelic98** [comment]
Hello @DDCreationStudios may I suggest contact page with contact form for easier visitor interaction, if you decide to do it I would also like to be assigned to the issue and do it, also please make sure to label it as hacktoberfest :D

**Comment by Createdd** [comment]
Closed due to inactivity and obsolete task for new design
