### ISSUE TITLE
Add initial friends.html page

### ISSUE THREAD

**Issue by Createdd** [DevelopersRising/DevelopersRising.github.io#6]
- add a link in the navbar
- create an own html file and link it properly
  - The page should contain sections for 
    - contributors referred to as "the team"
    - partners (companies and people, who we have been working with or still work with)
      - see the FCC Vienna repo for the first companies (section partners)

**Comment by MadhavBahl** [comment]
I will do it

**Comment by MadhavBahl** [comment]
I am on it @DDCreationStudios 👍
